const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '../data/portfolio.json');
const outputPath = path.join(__dirname, '../lib/data.ts');

function buildData() {
  console.log('Building data from portfolio.json...');
  
  try {
    const rawData = fs.readFileSync(dataPath, 'utf8');
    const data = JSON.parse(rawData);
    
    // Extract unique icons
    const uniqueIcons = [...new Set(data.skills.map(s => s.icon))].filter(Boolean);
    // Ensure Code2 is always imported as a fallback
    if (!uniqueIcons.includes('Code2')) uniqueIcons.push('Code2');
    
    // Generate TypeScript file
    const tsContent = `// This file is auto-generated by scripts/build-data.js
// Do not edit this file directly. Update data/portfolio.json instead.

import { LucideIcon, ${uniqueIcons.join(', ')} } from "lucide-react";

export const personalData = ${JSON.stringify(data.personal, null, 2)};

export const aboutData = ${JSON.stringify(data.about, null, 2)};

// Map string icon names to actual Lucide React components
const iconMap: Record<string, LucideIcon> = {
  ${uniqueIcons.join(',\n  ')}
};

export const skillsData = ${JSON.stringify(data.skills, null, 2)}.map(skill => ({
  ...skill,
  icon: iconMap[skill.icon] || Code2
}));

export const timelineData = ${JSON.stringify(data.timeline, null, 2)};

export const rolesData = ${JSON.stringify(data.roles, null, 2)};
`;

    // Ensure lib directory exists
    const libDir = path.dirname(outputPath);
    if (!fs.existsSync(libDir)) {
      fs.mkdirSync(libDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, tsContent, 'utf8');
    console.log('Successfully generated lib/data.ts');
  } catch (error) {
    console.error('Error building data:', error);
    process.exit(1);
  }
}

buildData();
